### ISSUE TITLE
Initial release checklist

### ISSUE THREAD

**Issue by annybs** [edge/lottery#2]
- [x] Language: change "release" to "draw"
- [x] Change page title in `index.html`
- [x] Add New Relic logging
- [x] Add up-to-date license comments
- [x] Add general code comments
